---
name: Build and Test

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]
  workflow_dispatch:
permissions:
  pull-requests: read   # allows SonarCloud to decorate PRs with analysis results

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Show version
        run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile coverage.out -json -v ./... > report.json

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            coverage.out
            report.json

  Analysis:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4

      - name: Get test reports
        uses: actions/download-artifact@v2
        with:
          name: test-reports
      - name: Analyze with SonarCloud

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        uses: sonarsource/sonarcloud-github-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the sonarcloud scanner
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            # -Dsonar.go.tests.reportPaths=report.json
            # -Dsonar.verbose=true
            -Dsonar.projectKey=mwmahlberg_swagger-ui
            -Dsonar.organization=mwmahlberg
            -Dsonar.projectName=swagger-ui
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go,**/*_generated*.go,**/*_generated/**,**/vendor/**,**/swagger-ui/**
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.links.homepage=https://github.com/mwmahlberg/swagger-ui
            -Dsonar.links.ci=https://github.com/mwmahlberg/swagger-ui/actions
            -Dsonar.links.scm=https://github.com/mwmahlberg/swagger-ui
            -Dsonar.links.issue=https://github.com/mwmahlberg/swagger-ui/issues
            -Dsonar.scm.provider=git
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # When you need the analysis to take place in a directory other than the one from which it was launched
            #-Dsonar.projectBaseDir= # optional, default is .
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false
